name: Schedule API Tests
on:
  schedules:
    -cron: "15 21 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4
      - name: Cypress run 
        uses: cypress-io/github-action@v6